In [1]:
import os
os.environ['CURL_CA_BUNDLE'] = ''
# Se importa la libreria
from src.scraping import scraping
# Se inializa el scraper
scrap = scraping()

c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'huggingface.co'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'huggingface.co'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'huggingface.co'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'huggingface.co'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

In [4]:
scrap.scraping_web("https://www.bancolombia.com/personas/tarjetas-de-credito?gclid=CjwKCAjw_YShBhAiEiwAMomsEPMQ87ZyilGGv9adjVhp_KEXC_tmcAF48uCj2hIPm8OnDR_kQLmi9xoC6coQAvD_BwE", False)

c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '51.68.207.81'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

'\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nTarjetas de crédito Bancolombia para que pagues fácilmente\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n{}\n\n\n\n\n\n\n\n\n\n\nZ7_OHHGG4G0P0JQD0Q1PHHU661K30\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nPersonas\n\n\n\nNegocios\n\n\n\nCorporativos\n\n\n\nNegocios especializados \n\n\n\n\n\nNegocios en Colombia\n\n\nBanca de Inversión\n                Bancolombia\n\n\n\nFiduciaria Bancolombia\n\n\n\nLeasing Bancolombia\n\n\n\nRenting Colombia\n\n\n\nValores Bancolombia\n\n\n\nFactoring Bancolombia\n\n\n\nAsset Management\n\n\n\n\n\nSufi\n\n\n\n\n\n\n\n\n\nEntidades en el exterior\n\n\nBancolombia Miami (USA)\n\n\n\nValores Banistmo\n\n\n\nSucursal Panamá\n\n\n\nBancolombia Panamá\n\n\n\nBancolombia Puerto\n                Rico\n\n\n\nBanistmo\n\n\n\nBanco Agrícola\n\n\n\nBAM (Banco Agromercantil\n                de\n                Guatemala)\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nTu360\n\n\n\nBlog\n\n\n\n\n\n\n\nTransparencia\n\n\nConsumidor\n\n\n\nSolicita Documentos\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nInicio\n\n\n\nNecesidades\n\n\n\n\n\nNecesidades\n\n\n\n                                                            Solicitud de documentos\n                                                          \n\n\n\n                                                            Soluciones de movilidad privada\n                                                          \n\n\n\n                                                              Soluciones de vivienda \n                                                          \n\n\n\n                                                              Soluciones de pago\n                                                          \n\n\n\n                                                           Soluciones de movilidad pública\n                                                          \n\n\n\n\n\nBanco para todos\n\n\n\n                                                            Para los niños                                                   \n                                                          \n\n\n\n                                                            Para los jóvenes                                                \n                                                          \n\n\n\n                                                            Para la familia \n                                                          \n\n\n\n\n\n\n\n\n\n\nColombianos en el exterior\n\n\n\nCliente Preferencial\n\n\nBanca Privada\n\n\nCliente Independiente\n\n\n\n\n\n\n\nOfertas y beneficios\n\n\n\nDisfruta opciones hechas para ti por ser nuestro cliente\n\n\n\n\n\n\n\nSolicitud de turno en sucursales\n\n\n\nAhorra tiempo, adelanta tu gestión desde donde estés\n\n\n\n\n\n\n\nCertificaciones Bancarias\n\n\n\nEncuentra lo que quieres cuando quieras, aquí te ayudamos\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nProductos y Servicios\n\n\n\n\n\nProductos y Servicios\n\n\nCuentas\n\n\nTarjetas Débito\n\n\nTarjetas de Crédito\n\n\nCréditos\n\n\n\n\n\n\n\n\n\nSeguros y asistencias\n\n\nInversiones\n\n\nGiros\n\n\nBancolombia A la Mano\n\n\n\n\n\n\n\n\n\nLeasing\n\n\nPagos\n\n\nCompra y venta de dólares\n                                                    \n\n\nVenta de usados\n\n\nRenta de vehículos\n\n\n\n\n\n\nCanales para tu servicio\n\n\n\n                                                        Sucursal Virtual Personas\n                                                      \n\n\n\n                                                        Solicitar productos\n                                                      \n\n\n\n                                                        Bancolombia App\n                                                      \n\n\n\n                                                        Corresponsal Bancario\n                                                      \n\n\n\n                                                        Cajero Multifuncional\n                                                      \n\n\n\n\n\n\n\n\n\n\n                                                        Sucursal telefónica\n                                                      \n\n\n\n                                                        Multipagos PSE\n                                                      \n\n\n\n                                                        Sucursal Física\n                                                      \n\n\n\n                                                        Cajero Automático\n                                                      \n\n\n\n\n\n\n\nConoce otros canales\n\n\n\n\n\n\n\n\n\nEducación Financiera\n\n\n\n\n\n\n\n\n\n\n\n\n\nSucursal Virtual Personas\n\nSucursal Virtual Personas\nSucursal Virtual Pymes\nSucursal Virtual Empresas\nPagos PSE\nVer más\n\n\nEntrar\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nSucursal Virtual Personas\n\nSucursal Virtual Personas\nSucursal Virtual Pymes\nSucursal Virtual Empresas\nPagos PSE\nVer más\n\n\n\nEntrar\n\n\n\n\nPersonas\n\n\n Solicitar productos \n\n\n\nNecesidades\n\n\nSolicitud de documentos\n\n\n\nSoluciones de movilidad privada\n\n\n\nSoluciones de vivienda\n\n\n\nSoluciones de pago\n\n\n\nSoluciones de movilidad pública\n\n\n\nPara los niños\n\n\n\nPara los jóvenes\n\n\n\nPara la familia\n\n\n\nColombianos en el exterior\n\n\n\nCliente Preferencial\n\n\n\nBanca Privada\n\n\n\nCliente Independiente\n\n\nOfertas y beneficios \n\n\n\nSolicitud de turno en sucursales\n\n\n\nTu360\n\n\n\n\n\n\n\nProductos y Servicios\n\n\nCuentas\n\n\n\nTarjetas Débito\n\n\n\nTarjetas de Crédito\n\n\n\nCréditos\n\n\n\n\nSeguros y asistencias\n\n\n\nInversiones\n\n\n\nGiros\n\n\nBancolombia A la Mano\n\n\n\nLeasing\n\n\nPagos\n\n\n\nCompra y venta de dólares\n\n\n\nVenta de usados\n\n\n\nRenta de vehículos\n\n\n\nConoce nuestros canales\n\n\n\nSucursal Virtual Personas\n\n\n\nSolicitar productos\n\n\n\nBancolombia App\n\n\n\nCorresponsal Bancario\n\n\n\nSucursal Telefónica\n\n\n\nMultipagos PSE\n\n\n\nSucursal Física\n\n\n\nCajero Automático\n\n\n\nCajero Multifuncional\n\n\n\n\n\n\n\nEducación Financiera\n\n\n\n\n\n\nNegocios\n\n\nSolicitud de documentos\n\n\nInicio\n\n\nActualízate\n\n\nProductos Financieros\n\n\nHerramientas\n\n\nAliados\n\n\nFormación\n\n\nSocial Selling\n\n\nIncoterms\n\n\n\n\nSectores\n\n\nAgroindustria\n\n\nComercio\n\n\n\n\nComercio Internacional\n\n\n\n\n\nCorporativos \n\n\nCorporativos\n\n\nTransacciones\n\n\n\n Solicitud de documentos\n                                        \n\n\n\nEmpieza tu negocio\n\n\n\nNecesidades PYMES\n\n\nSoluciones de financiación\n\n\n\nPagar y recaudar\n\n\n\nInversión de liquidez\n\n\n\n\n\nCobertura de riesgos\n\n\n\nEstructuración de negocios\n\n\n\nSolicitud de documentos\n\n\n\nAgroindustrias\n\n\n\nContratistas\n\n\n\nComercio\n\n\n\nColegios y universidades\n\n\n\nBeneficios para tu negocio y tus empleados\n\n\n\n\n\n\n\nNecesidades Empresas\n\n\nSoluciones de financiación\n\n\n\nAdministración de liquidez\n\n\n\nGestión de tesorería\n\n\n\nCobertura de riesgos\n\n\n\nEstructuración de negocios\n\n\n\nBienestar para tus empleados\n\n\n\nSolicitud de documentos\n\n\n\nExperiencia sectorial\n\n\n\n\n\n\n\nNecesidades Gobierno\n\n\nSoluciones de financiación\n\n\n\nAdministración de liquidez\n\n\n\nGestión de tesorería\n\n\n\nCobertura de riesgos\n\n\n\nEstructuración de negocios\n\n\n\nBienestar para tus empleados\n\n\n\nSolicitud de documentos\n\n\n\nExperiencia sectorial\n\n\n\n\n\n\n\nProductos y Servicios\n\n\nCréditos\n\n\n\nTarjetas de Crédito\n\n\n\nInversiones\n\n\n\nCuentas de Depósito\n\n\n\nCash Management\n\n\n\nDerivados\n\n\n\nSeguros\n\n\n\nNegocios Fiduciarios\n\n\n\nBanca de inversión\n\n\n\nLeasing\n\n\n\nFactoring\n\n\n\nRenting\n\n\n\nOperaciones en Moneda Extranjera\n\n\n\nSer Corresponsal Bancario\n\n\n\nConoce nuestros canales y administra tus productos en\n                                        forma ágil y segura\n\n\n\nSucursal Virtual Empresa\n\n\n\nLínea Empresas\n\n\n\nInmobiliaria y Vivienda\n\n\n\n\n\n\n\nCapital Inteligente\n\n\n\n\n\nNegocios Especializados\n\n\n\nBanca de Inversión Bancolombia\n\n\n\nFiduciaría Bancolombia\n\n\n\nLeasing Bancolombia\n\n\n\nRenting Colombia\n\n\n\nValores Bancolombia\n\n\n\nFactoring Bancolombia\n\n\n\nBancolombia Asset Management\n\n\n\n\n\nSufi\n\n\n\n\n\nValores Banistmo\n\n\n\nSucursal Panamá\n\n\n\nBancolombia Panamá\n\n\n\n\nBancolombia Puerto Rico\n\n\n\nBanistmo\n\n\n\nBanco Agrícola\n\n\n\nBAM (Banco Agromercantil de Guatemala)\n\n\n\n\n\nTu360\n\n\nBlog\n\n\nTransparencia\n\n\nConsumidor\n\n\n\n\n\n\n\n\n\n \n\n\nZ7_OHHGG4G0P0JQD0Q1PHHU661K33\n\n\n\n\n\n\n\n\n\n\n\n\n \n\n\nZ7_OHHGG4G0PORU30Q175D8OI10Q0\n\n\n\n\n\n\n\n\n\n\n\n\n \n\n\nZ7_OHHGG4G0PGV720Q7CR1B1L92H6\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nPersonas\n\n\n\n\n\nTarjetas de crédito\n\n\n\n\n\n\n\n \n\n\nZ7_OHHGG4G0P0JQD0Q1PHHU661KJ1\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                    Tarjetas de crédito\n                                \nEs el momento de elegir la tuya. Te ofrecemos tarjetas con beneficios que se adaptan a todas las necesidades, personalidades y estilos de vida.\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n \n\n\nZ7_OHHGG4G0P0JQD0Q1PHHU661KT3\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nTDC_2022\n\n\n\n\n\n\n\n\n\n\n \n\n\nZ7_OHHGG4G0POF7C0QDBVBVLB3E90\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nTasas\nConoce todas las tasas que aplican para las operaciones de tarjetas de crédito.\n\n\nConocer tasas\n\n\n\n\n\n \n\n\nZ7_OHHGG4G0POJ570641IBJAL9NJ2\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nCaracterísticas generales\nConoce las características generales de tu tarjeta de crédito Bancolombia.\n\n\nConocer \n\n\n\n\n\n \n\n\nZ7_OHHGG4G0P0JQD0Q1PHHU661CD1\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                                    \n                            Conoce las asistencias y seguros de tus tarjetas de crédito\n                        \n                        \n\n                        \n                            Con Bancolombia tienes mucho más que un medio de pago. Conoce las protecciones para compras, viajes, hogar y vehículo.\n                                                \n                        \n\n\n\nQuiero conocerlas \n\n\n\n\n\n\n \n\n\nZ7_OHHGG4G0P0JQD0Q1PHHU661KJ0\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nTe puede interesar\n\narrow2-down\n\n\n\n\n\nAcerca de nosotros\n\n\n\nTrabaja con nosotros\n\n\nGrupo\n                                        Bancolombia\n\n\nCentro de Ayuda\n\n\nCanales\n\n\nPuntos de atención\n\n\nAccesibilidad\n\n\n\n\n\n\n\n\nLegales\n\narrow2-down\n\n\n\n\n\n\n\nGobierno\n                                                Corporativo\n\n\nSARLAFT\n\n\nProtección de datos\n\n\nTérminos y Condiciones de\n                                                uso\n\n\nProceso licitatorio seguros 2023-2025\n\n\nTarifas\n\n\nAutorización para tratamiento de datos personales\n\n\n\n\n\n\nTransparencia y Acceso a la Información\n\n\nAtención al\n                                                Consumidor Financiero\n\n\nDefensor del\n                                                Consumidor Financiero\n\n\nnotificacijudicial@bancolombia.com.co\n\n\n\n\n\n\n\n\n\n\nContáctanos\n\narrow2-down\n\n\n\n\n\n                                    Carrera 48 # 26 - 85 Medellín – Colombia\n                                \n\nBogotá +57 (601) 343 0000\n\n\nMedellín +57 (604) 510 9000\n\n\nLínea gratuita resto del país:  01 8000 9 12345\n\n\nLínea ética 01 8000 524499\n\n\n\n\n\n\n\n\n\n                                Productos y servicios de Banca, Fiducia, Banca de Inversión, Financiamiento, además\n                                del\n                                portafolio\n                                ofrecido por las entidades del exterior en Panamá, Estados Unidos y Puerto Rico.\n                            \n\n\n\nBANCOLOMBIA S.A. Establecimiento Bancario\n\n\n\n\n\n \n\n\n\n\nfacebook\n\n\n\n\n\n\n\n\n\ninstagram\n\n\n\n\nyoutube\n\n\n\n\nlinkedin\n\n\n\n\n\n\n\n\n\n\n\n\n\nbancolombia-horizontal\n\n                        Copyright © 2021 Grupo Bancolombia\n                    \n\n\n\n\n\n\n\n\n\n\n\n\n \n\n\n\n\n\n\n\n\n Deferred Modules \n\n\n\n\n\n\n${title}${badge}\n\n\n\n${loading}\n\n\n\n\n\n\n Deferred Modules \n\n\n '

In [5]:
# Se declara una lista de busquedas
company_serch = ["PROCTER & GAMBLE-PG-NEWS"]
# Se realizar las busquedas en el tiempo deseado (un dia)
df = scrap.GoogleNews(company_serch, "2019-08-01", 1, )

------------------------------------------------------------------
----------------------- Iniciando --------------------------------
------------------------------------------------------------------
Fecha de inicio: 07/31/2019
Fecha final: 08/01/2019

  0%|          | 0/1 [00:00<?, ?it/s]

-----------------------nueva version--------------------
https://www.google.com/search?q=PROCTER%20%26%20GAMBLE-PG-NEWS&lr=lang_en&biw=1920&bih=976&source=lnt&&tbs=lr:lang_1en,cdr:1,cd_min:07/31/2019,cd_max:08/01/2019,sbd:1&tbm=nws&start=0

Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 198, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    p.prepare(
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 392, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?

###############################
[<a class="gyPpGe" data-ved="0ahUKEwivgL2OvvaDAxXzqZUCHUCJAtEQ67oDCAU" jsaction="i3viod" jsname="BKxS1e" role="link" tabindex="0">Skip to main content</a>, <a class="gyPpGe" data-jsarwt="1" data-usg="AOvVaw1ybrggvbdAH2R4qRmiXlw8" data-ved="0ahUKEwivgL2OvvaDAxXzqZUCHUCJAtEQwcMDCAY" href="https://support.google.com/websearch/answer/181196?hl=en-CO" jsname="KI37ad">Accessibility help</a>, <a class="zItAnd FOU1zf cLIEsf GMT2kb" data-hveid="CAYQAg" data-ved="2ahUKEwivgL2OvvaDAxXzqZUCHUCJAtEQ0pQJegQIBhAC" href="/search?q=PROCTER+%26+GAMBLE-PG-NEWS&amp;lr=lang_en&amp;safe=active&amp;sca_esv=601121294&amp;hl=en&amp;gl=en&amp;biw=1920&amp;bih=976&amp;source=lnms&amp;sa=X&amp;ved=2ahUKEwivgL2OvvaDAxXzqZUCHUCJAtEQ0pQJegQIBhAC"><svg aria-hidden="true" class="mUKzod QIkCq" focusable="false" viewbox="0 0 24 24"><path d="M0 0h24v24H0z" fill="none"></path><path d="M16.41 5.41L15 4l-8 8 8 8 1.41-1.41L9.83 12"></path></svg><div class="O3S9Rb">All</div></a>, <a aria-current="page" class="zItAnd FOU1zf MgQdud" data-hveid="CAYQBA" data-ved="2ahUKEwivgL2OvvaDAxXzqZUCHUCJAtEQ0pQJegQIBhAE"><div class="O3S9Rb">News</div></a>, <a class="zItAnd FOU1zf" data-hveid="CAYQBg" data-ved="2ahUKEwivgL2OvvaDAxXzqZUCHUCJAtEQ0pQJegQIBhAG" href="/search?q=PROCTER+%26+GAMBLE-PG-NEWS&amp;lr=lang_en&amp;safe=active&amp;sca_esv=601121294&amp;hl=en&amp;gl=en&amp;biw=1920&amp;bih=976&amp;tbs=lr:lang_1en,cdr:1,cd_min:07/31/2019,cd_max:08/01/2019&amp;tbm=isch&amp;source=lnms&amp;sa=X&amp;ved=2ahUKEwivgL2OvvaDAxXzqZUCHUCJAtEQ0pQJegQIBhAG"><div class="O3S9Rb">Images</div></a>, <a class="zItAnd FOU1zf" data-hveid="CAYQCA" data-ved="2ahUKEwivgL2OvvaDAxXzqZUCHUCJAtEQ0pQJegQIBhAI" href="/search?q=PROCTER+%26+GAMBLE-PG-NEWS&amp;lr=lang_en&amp;safe=active&amp;sca_esv=601121294&amp;hl=en&amp;gl=en&amp;biw=1920&amp;bih=976&amp;tbs=lr:lang_1en,cdr:1,cd_min:07/31/2019,cd_max:08/01/2019&amp;tbm=vid&amp;source=lnms&amp;sa=X&amp;ved=2ahUKEwivgL2OvvaDAxXzqZUCHUCJAtEQ0pQJegQIBhAI"><div class="O3S9Rb">Videos</div></a>, <a class="zItAnd FOU1zf" data-hveid="CAYQCg" data-jsarwt="1" data-usg="AOvVaw3ncpsFY3TZrMOryIAGv9pM" data-ved="2ahUKEwivgL2OvvaDAxXzqZUCHUCJAtEQi6AMegQIBhAK" href="https://maps.google.com/maps?hl=en&amp;gl=en&amp;q=PROCTER+%26+GAMBLE-PG-NEWS&amp;lr=lang_en&amp;biw=1920&amp;bih=976&amp;safe=active&amp;um=1&amp;ie=UTF-8"><div class="O3S9Rb">Maps</div></a>, <a class="WlydOe" data-jsarwt="1" data-usg="AOvVaw1wkEiyTb0kVQtod7SXRBLf" data-ved="2ahUKEwivgL2OvvaDAxXzqZUCHUCJAtEQxfQBKAB6BAgJEAE" href="https://www.thenewsminute.com/atom/why-digital-transformations-fail-former-pg-vp-tony-saldanha-shares-his-insights-106532" jsname="YKoRaf"><div class="lSfe4c r5bEn aI5QMe"><div class="gpjNTe"><div class="YEMaTe JFSfwc" style="background-color:#c3c3b6;height:92px;width:92px"><div class="uhHOwf BYbUcd" style="height:92px;width:92px"><img alt="" data-deferred="1" id="dimg_3" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///////yH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="/></div></div></div><div class="SoAPf"><div class="MgUUmf NUnG9d"><g-img class="QyR1Ze ZGomKf" style="margin-right:8px"><img alt="" class="YQ4gaf zr758c" data-deferred="1" height="16" id="dimg_7" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///////yH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" style="border-radius:2px 2px 2px 2px" width="16"/></g-img><span>The News Minute</span></div><div aria-level="3" class="n0jPhd ynAwRc MBeuO jBgGLd OSrXXb" role="heading">‘Why digital transformations fail’: Former P&amp;G VP Tony Saldanha <br/>shares his
insights</div><div class="GI74Re jBgGLd OSrXXb" style="margin-top:8px">'Why digital transformations fail' is also the name of the book authored by
Tony <br/>where he elaborates how companies can overcome this problem.</div><span class="lO8SBd" tabindex="-1">.</span><div class="OSrXXb rbYSKb LfVVr" style="bottom:0px"><span>Aug 1, 2019</span></div></div></div></a>, <a class="WlydOe" data-jsarwt="1" data-usg="AOvVaw1BH_zKA2EJN6HP8qi_lpjH" data-ved="2ahUKEwivgL2OvvaDAxXzqZUCHUCJAtEQxfQBKAB6BAgLEAE" href="https://insidefmcg.com.au/2019/08/01/pg-and-unilever-dominate-australian-shampoo-market%EF%BB%BF/" jsname="YKoRaf"><div class="lSfe4c r5bEn aI5QMe"><div class="gpjNTe"><div class="YEMaTe JFSfwc" style="background-color:#f8f9fa;height:92px;width:92px"><div class="uhHOwf BYbUcd" style="height:92px;width:92px"><img alt="" data-deferred="1" id="dimg_5" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///////yH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="/></div></div></div><div class="SoAPf"><div class="MgUUmf NUnG9d"><g-img class="QyR1Ze ZGomKf" style="margin-right:8px"><img alt="" class="YQ4gaf zr758c" data-deferred="1" height="16" id="dimg_9" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///////yH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" style="border-radius:2px 2px 2px 2px" width="16"/></g-img><span>Inside FMCG</span></div><div aria-level="3" class="n0jPhd ynAwRc MBeuO jBgGLd OSrXXb" role="heading">P&amp;G and Unilever dominate Australian shampoo market﻿</div><div class="GI74Re jBgGLd OSrXXb" style="margin-top:8px">Major consumer goods brands Procter &amp; Gamble (P&amp;G) and Unilever are
<br/>dominating the local shampoo market with Head &amp; Shoulders leading the pack
as <br/>the most...</div><span class="lO8SBd" tabindex="-1">.</span><div class="OSrXXb rbYSKb LfVVr" style="bottom:0px"><span>Aug 1, 2019</span></div></div></div></a>, <a class="WlydOe" data-jsarwt="1" data-usg="AOvVaw1AtQFwBvIzZKA7ePRihiWl" data-ved="2ahUKEwivgL2OvvaDAxXzqZUCHUCJAtEQxfQBKAB6BAgNEAE" href="https://www.washingtontimes.com/news/2019/jul/31/gillettes-toxic-masculinity-ad-haunts-pg-as-shavin/" jsname="YKoRaf"><div class="lSfe4c r5bEn aI5QMe"><div class="gpjNTe"><div class="YEMaTe JFSfwc" style="background-color:#f8f9fa;height:92px;width:92px"><div class="uhHOwf BYbUcd" style="height:92px;width:92px"><img alt="" data-deferred="1" id="dimg_1" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///////yH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="/></div></div></div><div class="SoAPf"><div class="MgUUmf NUnG9d"><g-img class="QyR1Ze ZGomKf" style="margin-right:8px"><img alt="" class="YQ4gaf zr758c" data-deferred="1" height="16" id="dimg_11" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///////yH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" style="border-radius:2px 2px 2px 2px" width="16"/></g-img><span>Washington Times</span></div><div aria-level="3" class="n0jPhd ynAwRc MBeuO jBgGLd OSrXXb" role="heading">Gillette's 'toxic masculinity' ad haunts P&amp;G as shaving giant takes $8B
<br/>writedown</div><div class="GI74Re jBgGLd OSrXXb" style="margin-top:8px">Gillette's infamous "toxic masculinity" ad may cost Procter &amp; Gamble more
than <br/>anyone imagined in January.</div><span class="lO8SBd" tabindex="-1">.</span><div class="OSrXXb rbYSKb LfVVr" style="bottom:0px"><span>Jul 31, 2019</span></div></div></div></a>]
----------
----------
https://support.google.com/websearch/answer/181196?hl=en-CO
----------
/search?q=PROCTER+%26+GAMBLE-PG-NEWS&lr=lang_en&safe=active&sca_esv=601121294&hl=en&gl=en&biw=1920&bih=976&source=lnms&sa=X&ved=2ahUKEwivgL2OvvaDAxXzqZUCHUCJAtEQ0pQJegQIBhAC
----------
----------
/search?q=PROCTER+%26+GAMBLE-PG-NEWS&lr=lang_en&safe=active&sca_esv=601121294&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:07/31/2019,cd_max:08/01/2019&tbm=isch&source=lnms&sa=X&ved=2ahUKEwivgL2OvvaDAxXzqZUCHUCJAtEQ0pQJegQIBhAG
----------
/search?q=PROCTER+%26+GAMBLE-PG-NEWS&lr=lang_en&safe=active&sca_esv=601121294&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:07/31/2019,cd_max:08/01/2019&tbm=vid&source=lnms&sa=X&ved=2ahUKEwivgL2OvvaDAxXzqZUCHUCJAtEQ0pQJegQIBhAI
----------
https://maps.google.com/maps?hl=en&gl=en&q=PROCTER+%26+GAMBLE-PG-NEWS&lr=lang_en&biw=1920&bih=976&safe=active&um=1&ie=UTF-8
----------
https://www.thenewsminute.com/atom/why-digital-transformations-fail-former-pg-vp-tony-saldanha-shares-his-insights-106532
----------
https://insidefmcg.com.au/2019/08/01/pg-and-unilever-dominate-australian-shampoo-market%EF%BB%BF/
----------
https://www.washingtontimes.com/news/2019/jul/31/gillettes-toxic-masculinity-ad-haunts-pg-as-shavin/
Antes del sleep
Despues del sleep

c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\pip_system_certs\wrapt_requests.py:71: UserWarning: Failed to patch SSL settings for unverified requests (unsupported version of urllib3?)
This may lead to errors when urllib3 tries to modify verify_mode.
Please report an issue at https://gitlab.com/alelec/pip-system-certs with your
python version included in the description

  warnings.warn(
c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '104.18.254.76'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\setuptools\distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  warnings.warn(
Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.
c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\transformers\pipelines\text_classification.py:104: UserWarning: `return_all_scores` is now deprecated,  if want a similar functionality use `top_k=None` instead of `return_all_scores=True` or `top_k=1` instead of `return_all_scores=False`.
  warnings.warn(

Antes del sleep

Exception in thread Thread-8:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 198, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    p.prepare(
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 392, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/search?q=PROCTER+%26+GAMBLE-PG-NEWS&lr=lang_en&safe=active&sca_esv=601121294&hl=en&gl=en&biw=1920&bih=976&source=lnms&sa=X&ved=2ahUKEwivgL2OvvaDAxXzqZUCHUCJAtEQ0pQJegQIBhAC': No scheme supplied. Perhaps you meant http:///search?q=PROCTER+%26+GAMBLE-PG-NEWS&lr=lang_en&safe=active&sca_esv=601121294&hl=en&gl=en&biw=1920&bih=976&source=lnms&sa=X&ved=2ahUKEwivgL2OvvaDAxXzqZUCHUCJAtEQ0pQJegQIBhAC?

Despues del sleep
Antes del sleep

Exception in thread Thread-9:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 198, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    p.prepare(
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 392, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?

Despues del sleep
Antes del sleep

Exception in thread Thread-10:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 198, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=PROCTER+%26+GAMBLE-PG-NEWS&lr=lang_en&safe=active&sca_esv=601121294&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:07/31/2019,cd_max:08/01/2019&tbm=isch&source=lnms&sa=X&ved=2ahUKEwivgL2OvvaDAxXzqZUCHUCJAtEQ0pQJegQIBhAG'

Despues del sleep
Antes del sleep

Exception in thread Thread-11:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 198, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=PROCTER+%26+GAMBLE-PG-NEWS&lr=lang_en&safe=active&sca_esv=601121294&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:07/31/2019,cd_max:08/01/2019&tbm=vid&source=lnms&sa=X&ved=2ahUKEwivgL2OvvaDAxXzqZUCHUCJAtEQ0pQJegQIBhAI'

Despues del sleep
Antes del sleep
Despues del sleep

c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\pip_system_certs\wrapt_requests.py:71: UserWarning: Failed to patch SSL settings for unverified requests (unsupported version of urllib3?)
This may lead to errors when urllib3 tries to modify verify_mode.
Please report an issue at https://gitlab.com/alelec/pip-system-certs with your
python version included in the description

  warnings.warn(
c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '104.16.241.204'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '104.16.241.204'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

Antes del sleep
Despues del sleep

c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '51.68.207.81'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

Antes del sleep
Despues del sleep

c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '173.192.21.89'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

Antes del sleep
Despues del sleep

c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '203.24.108.179'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

Antes del sleep

100%|██████████| 1/1 [07:10<00:00, 430.63s/it]

Despues del sleep
-------------------------------
------ creando dataframe ------
-------------------------------

In [6]:
df

,company,Year,Month,Day,date,media,description,title,link,Text,word_count
0,PROCTER & GAMBLE-PG-NEWS,2019,8,1,2019/08/01,,,,https://www.thenewsminute.com/atom/why-digital...,why digital fail former pg vp tony saldanha sh...,1051
1,PROCTER & GAMBLE-PG-NEWS,2019,8,1,2019/08/01,,,,https://insidefmcg.com.au/2019/08/01/pg-and-un...,size is the company you work for 09employees 1...,600
2,PROCTER & GAMBLE-PG-NEWS,2019,8,1,2019/08/01,,,,https://www.washingtontimes.com/news/2019/jul/...,gillettes toxic masculinity ad haunts pg as sh...,900

In [13]:
# Se declara una lista de busquedas
company_serch = ["EXXON MOBIL-XOM-NEWS"]
# Se realizar las busquedas en el tiempo deseado (un dia)
df = scrap.GoogleNews(company_serch, "2019-07-01", 1, type_time="MS")

------------------------------------------------------------------
----------------------- Iniciando --------------------------------
------------------------------------------------------------------
Fecha de inicio: 06/01/2019
Fecha final: 07/01/2019

  0%|          | 0/1 [00:00<?, ?it/s]

-----------------------nueva version--------------------
https://www.google.com/search?q=EXXON%20MOBIL-XOM-NEWS&lr=lang_en&biw=1920&bih=976&source=lnt&&tbs=lr:lang_1en,cdr:1,cd_min:06/01/2019,cd_max:07/01/2019,sbd:1&tbm=nws&start=0

Exception in thread Thread-20:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    p.prepare(
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 392, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?

###############################
[<a class="gyPpGe" data-ved="0ahUKEwiohMHu9oyEAxVbRjABHQvCCGkQ67oDCAU" jsaction="i3viod" jsname="BKxS1e" role="link" tabindex="0">Skip to main content</a>, <a class="gyPpGe" data-jsarwt="1" data-usg="AOvVaw1ybrggvbdAH2R4qRmiXlw8" data-ved="0ahUKEwiohMHu9oyEAxVbRjABHQvCCGkQwcMDCAY" href="https://support.google.com/websearch/answer/181196?hl=en-CO" jsname="KI37ad">Accessibility help</a>, <a class="zItAnd FOU1zf cLIEsf GMT2kb" data-hveid="CAYQAg" data-ved="2ahUKEwiohMHu9oyEAxVbRjABHQvCCGkQ0pQJegQIBhAC" href="/search?q=EXXON+MOBIL-XOM-NEWS&amp;lr=lang_en&amp;safe=active&amp;sca_esv=3cbe9f3cb5d0638a&amp;hl=en&amp;gl=en&amp;biw=1920&amp;bih=976&amp;source=lnms&amp;sa=X&amp;ved=2ahUKEwiohMHu9oyEAxVbRjABHQvCCGkQ0pQJegQIBhAC"><svg aria-hidden="true" class="mUKzod QIkCq" focusable="false" viewbox="0 0 24 24"><path d="M0 0h24v24H0z" fill="none"></path><path d="M16.41 5.41L15 4l-8 8 8 8 1.41-1.41L9.83 12"></path></svg><div class="O3S9Rb">All</div></a>, <a aria-current="page" class="zItAnd FOU1zf MgQdud" data-hveid="CAYQBA" data-ved="2ahUKEwiohMHu9oyEAxVbRjABHQvCCGkQ0pQJegQIBhAE"><div class="O3S9Rb">News</div></a>, <a class="zItAnd FOU1zf" data-hveid="CAYQBg" data-ved="2ahUKEwiohMHu9oyEAxVbRjABHQvCCGkQ0pQJegQIBhAG" href="/search?q=EXXON+MOBIL-XOM-NEWS&amp;lr=lang_en&amp;safe=active&amp;sca_esv=3cbe9f3cb5d0638a&amp;hl=en&amp;gl=en&amp;biw=1920&amp;bih=976&amp;tbs=lr:lang_1en,cdr:1,cd_min:06/01/2019,cd_max:07/01/2019&amp;tbm=vid&amp;source=lnms&amp;sa=X&amp;ved=2ahUKEwiohMHu9oyEAxVbRjABHQvCCGkQ0pQJegQIBhAG"><div class="O3S9Rb">Videos</div></a>, <a class="zItAnd FOU1zf" data-hveid="CAYQCA" data-ved="2ahUKEwiohMHu9oyEAxVbRjABHQvCCGkQ0pQJegQIBhAI" href="/search?q=EXXON+MOBIL-XOM-NEWS&amp;lr=lang_en&amp;safe=active&amp;sca_esv=3cbe9f3cb5d0638a&amp;hl=en&amp;gl=en&amp;biw=1920&amp;bih=976&amp;tbs=lr:lang_1en,cdr:1,cd_min:06/01/2019,cd_max:07/01/2019&amp;tbm=isch&amp;source=lnms&amp;sa=X&amp;ved=2ahUKEwiohMHu9oyEAxVbRjABHQvCCGkQ0pQJegQIBhAI"><div class="O3S9Rb">Images</div></a>, <a class="zItAnd FOU1zf" data-hveid="CAYQCg" data-ved="2ahUKEwiohMHu9oyEAxVbRjABHQvCCGkQ0pQJegQIBhAK" href="/search?q=EXXON+MOBIL-XOM-NEWS&amp;lr=lang_en&amp;safe=active&amp;sca_esv=3cbe9f3cb5d0638a&amp;hl=en&amp;gl=en&amp;biw=1920&amp;bih=976&amp;tbs=lr:lang_1en,cdr:1,cd_min:06/01/2019,cd_max:07/01/2019,sbd:1&amp;tbm=bks&amp;source=lnms&amp;sa=X&amp;ved=2ahUKEwiohMHu9oyEAxVbRjABHQvCCGkQ0pQJegQIBhAK"><div class="O3S9Rb">Books</div></a>, <a class="WlydOe" data-jsarwt="1" data-usg="AOvVaw2DmrjRa13ZkmMGyamzc2ov" data-ved="2ahUKEwiohMHu9oyEAxVbRjABHQvCCGkQxfQBKAB6BAgHEAE" href="https://finance.yahoo.com/news/w-t-offshore-acquire-200m-123912224.html" jsname="YKoRaf"><div class="lSfe4c r5bEn aI5QMe"><div class="gpjNTe"><div class="YEMaTe JFSfwc" style="background-color:#f8f9fa;height:92px;width:92px"><div class="uhHOwf BYbUcd" style="height:92px;width:92px"><img alt="" data-deferred="1" id="dimg_9" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///////yH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="/></div></div></div><div class="SoAPf"><div class="MgUUmf NUnG9d"><g-img class="QyR1Ze ZGomKf" style="margin-right:8px"><img alt="" class="YQ4gaf zr758c" data-deferred="1" height="16" id="dimg_27" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///////yH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" style="border-radius:2px 2px 2px 2px" width="16"/></g-img><span>Yahoo Finance</span></div><div aria-level="3" class="n0jPhd ynAwRc MBeuO jBgGLd OSrXXb" role="heading">W&amp;T Offshore to Acquire $200M GoM Assets From ExxonMobil</div><div class="GI74Re jBgGLd OSrXXb" style="margin-top:8px">W&amp;T Offshore, Inc. WTI recently agreed to acquire Exxon Mobil Corporation's
XOM <br/>stakes in hydrocarbon producing assets located offshore Alabama in the
U.S....</div><span class="lO8SBd" tabindex="-1">.</span><div class="OSrXXb rbYSKb LfVVr" style="bottom:0px"><span>Jun 28, 2019</span></div></div></div></a>, <a class="WlydOe" data-jsarwt="1" data-usg="AOvVaw2pEmQqYfD4IKnX6x6JNH-6" data-ved="2ahUKEwiohMHu9oyEAxVbRjABHQvCCGkQxfQBKAB6BAgQEAE" href="https://www.investopedia.com/news/why-amazon-microsoft-netflix-pose-risk-stock-market/" jsname="YKoRaf"><div class="lSfe4c r5bEn aI5QMe"><div class="gpjNTe"><div class="YEMaTe JFSfwc" style="background-color:#f8f9fa;height:92px;width:92px"><div class="uhHOwf BYbUcd" style="height:92px;width:92px"><img alt="" data-deferred="1" id="dimg_17" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///////yH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="/></div></div></div><div class="SoAPf"><div class="MgUUmf NUnG9d"><g-img class="QyR1Ze ZGomKf" style="margin-right:8px"><img alt="" class="YQ4gaf zr758c" data-deferred="1" height="16" id="dimg_23" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///////yH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" style="border-radius:2px 2px 2px 2px" width="16"/></g-img><span>Investopedia</span></div><div aria-level="3" class="n0jPhd ynAwRc MBeuO jBgGLd OSrXXb" role="heading">Why Amazon, Microsoft, Netflix Pose a Risk to Stock Market</div><div class="GI74Re jBgGLd OSrXXb" style="margin-top:8px">Tech stocks were supposed to falter as valuations soared, but they continue
to <br/>dominate the market.</div><span class="lO8SBd" tabindex="-1">.</span><div class="OSrXXb rbYSKb LfVVr" style="bottom:0px"><span>Jun 25, 2019</span></div></div></div></a>, <a class="WlydOe" data-jsarwt="1" data-usg="AOvVaw1hyOeBSfAODN70kfmBonA7" data-ved="2ahUKEwiohMHu9oyEAxVbRjABHQvCCGkQxfQBKAB6BAgNEAE" href="https://www.investopedia.com/news/10-most-loved-stocks-etfs/" jsname="YKoRaf"><div class="lSfe4c r5bEn aI5QMe"><div class="gpjNTe"><div class="YEMaTe JFSfwc" style="background-color:#f8f9fa;height:92px;width:92px"><div class="uhHOwf BYbUcd" style="height:92px;width:92px"><img alt="" data-deferred="1" id="dimg_3" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///////yH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="/></div></div></div><div class="SoAPf"><div class="MgUUmf NUnG9d"><g-img class="QyR1Ze ZGomKf" style="margin-right:8px"><img alt="" class="YQ4gaf zr758c" data-deferred="1" height="16" id="dimg_31" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///////yH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" style="border-radius:2px 2px 2px 2px" width="16"/></g-img><span>Investopedia</span></div><div aria-level="3" class="n0jPhd ynAwRc MBeuO jBgGLd OSrXXb" role="heading">10 Most-Loved Stocks in ETFs</div><div class="GI74Re jBgGLd OSrXXb" style="margin-top:8px">The growth in popularity of exchange-traded funds, known simply as ETFs, is
no <br/>secret. What investors may be less aware of, however, is which stocks
are the...</div><span class="lO8SBd" tabindex="-1">.</span><div class="OSrXXb rbYSKb LfVVr" style="bottom:0px"><span>Jun 25, 2019</span></div></div></div></a>, <a class="WlydOe" data-jsarwt="1" data-usg="AOvVaw1vSIh9Ei151ODPzd7KkbLp" data-ved="2ahUKEwiohMHu9oyEAxVbRjABHQvCCGkQxfQBKAB6BAgKEAE" href="https://money.usnews.com/investing/stock-market-news/slideshows/9-oil-stocks-to-buy-when-oil-prices-are-low" jsname="YKoRaf"><div class="lSfe4c r5bEn aI5QMe"><div class="gpjNTe"><div class="YEMaTe JFSfwc" style="background-color:#f8f9fa;height:92px;width:92px"><div class="uhHOwf BYbUcd" style="height:92px;width:92px"><img alt="" data-deferred="1" id="dimg_2" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///////yH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="/></div></div></div><div class="SoAPf"><div class="MgUUmf NUnG9d"><g-img class="QyR1Ze ZGomKf" style="margin-right:8px"><img alt="" class="YQ4gaf zr758c" data-deferred="1" height="16" id="dimg_33" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///////yH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" style="border-radius:2px 2px 2px 2px" width="16"/></g-img><span>US News Money</span></div><div aria-level="3" class="n0jPhd ynAwRc MBeuO jBgGLd OSrXXb" role="heading">9 Oil Stocks to Buy When Oil Prices Are Low</div><div class="GI74Re jBgGLd OSrXXb" style="margin-top:8px">Slowing global economic growth and demand concerns have WTI crude oil
prices <br/>down more than 20% from a year ago. Oil investors were hoping for
much higher...</div><span class="lO8SBd" tabindex="-1">.</span><div class="OSrXXb rbYSKb LfVVr" style="bottom:0px"><span>Jun 25, 2019</span></div></div></div></a>, <a class="WlydOe" data-jsarwt="1" data-usg="AOvVaw2s-26cECa3cI0HLqjRoGeK" data-ved="2ahUKEwiohMHu9oyEAxVbRjABHQvCCGkQxfQBKAB6BAgOEAE" href="https://finance.yahoo.com/news/where-exxonmobil-5-years-203300616.html" jsname="YKoRaf"><div class="lSfe4c r5bEn aI5QMe"><div class="gpjNTe"><div class="YEMaTe JFSfwc" style="background-color:#f8f9fa;height:92px;width:92px"><div class="uhHOwf BYbUcd" style="height:92px;width:92px"><img alt="" data-deferred="1" id="dimg_1" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///////yH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="/></div></div></div><div class="SoAPf"><div class="MgUUmf NUnG9d"><g-img class="QyR1Ze ZGomKf" style="margin-right:8px"><img alt="" class="YQ4gaf zr758c" data-deferred="1" height="16" id="dimg_35" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///////yH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" style="border-radius:2px 2px 2px 2px" width="16"/></g-img><span>Yahoo Finance</span></div><div aria-level="3" class="n0jPhd ynAwRc MBeuO jBgGLd OSrXXb" role="heading">Where Will ExxonMobil Be in 5 Years?</div><div class="GI74Re jBgGLd OSrXXb" style="margin-top:8px">In March 2018, ExxonMobil (NYSE: XOM) announced a bold vision for the
future. <br/>The oil behemoth planned to increase its investment spending rate
over the...</div><span class="lO8SBd" tabindex="-1">.</span><div class="OSrXXb rbYSKb LfVVr" style="bottom:0px"><span>Jun 15, 2019</span></div></div></div></a>, <a class="WlydOe" data-jsarwt="1" data-usg="AOvVaw3b27uvjEsdo_FLSc7J90Vk" data-ved="2ahUKEwiohMHu9oyEAxVbRjABHQvCCGkQxfQBKAB6BAgPEAE" href="https://seekingalpha.com/news/3471071-conocophillips-hess-cut-from-norway-wealth-fund?source=content_type%3Areact%7Csection%3Asummary%7Csection_asset%3Anews_news%7Cfirst_level_url%3Asymbol%7Cbutton%3ATitle%7Clock_status%3ANo%7Cline%3A27" jsname="YKoRaf"><div class="lSfe4c r5bEn aI5QMe"><div class="gpjNTe"><div class="YEMaTe JFSfwc" style="background-color:#fc7316;height:92px;width:92px"><div class="uhHOwf BYbUcd" style="height:92px;width:92px"><img alt="" data-deferred="1" id="dimg_11" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///////yH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="/></div></div></div><div class="SoAPf"><div class="MgUUmf NUnG9d"><g-img class="QyR1Ze ZGomKf" style="margin-right:8px"><img alt="" class="YQ4gaf zr758c" data-deferred="1" height="16" id="dimg_19" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///////yH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" style="border-radius:2px 2px 2px 2px" width="16"/></g-img><span>Seeking Alpha</span></div><div aria-level="3" class="n0jPhd ynAwRc MBeuO jBgGLd OSrXXb" role="heading">ConocoPhillips, Hess cut from Norway wealth fund (NYSE:COP)</div><div class="GI74Re jBgGLd OSrXXb" style="margin-top:8px">Norway's $1T sovereign wealth fund will no longer be able to invest in
<br/>ConocoPhillips (NYSE:COP) and Hess (NYSE:HES) after a list used to decide
<br/>which...</div><span class="lO8SBd" tabindex="-1">.</span><div class="OSrXXb rbYSKb LfVVr" style="bottom:0px"><span>Jun 13, 2019</span></div></div></div></a>, <a class="WlydOe" data-jsarwt="1" data-usg="AOvVaw036uh1A0lDzLmAMXHo9MTS" data-ved="2ahUKEwiohMHu9oyEAxVbRjABHQvCCGkQxfQBKAB6BAgMEAE" href="https://www.bizjournals.com/houston/news/2019/06/13/exxon-and-sabic-ok-construction-of-giant-south.html" jsname="YKoRaf"><div class="lSfe4c r5bEn aI5QMe"><div class="gpjNTe"><div class="YEMaTe JFSfwc" style="background-color:#f8f9fa;height:92px;width:92px"><div class="uhHOwf BYbUcd" style="height:92px;width:92px"><img alt="" data-deferred="1" id="dimg_13" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///////yH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="/></div></div></div><div class="SoAPf"><div class="MgUUmf NUnG9d"><g-img class="QyR1Ze ZGomKf" style="margin-right:8px"><img alt="" class="YQ4gaf zr758c" data-deferred="1" height="16" id="dimg_28" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///////yH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" style="border-radius:2px 2px 2px 2px" width="16"/></g-img><span>The Business Journals</span></div><div aria-level="3" class="n0jPhd ynAwRc MBeuO jBgGLd OSrXXb" role="heading">Exxon and SABIC OK construction of giant South Texas plant - <br/>Houston
Business Journal</div><div class="GI74Re jBgGLd OSrXXb" style="margin-top:8px">Gulf Coast Growth Ventures, a joint venture between oil giant Exxon Mobile
and <br/>Saudi Basic Industries Corp, plans to build a $10 billion plastics
plant just...</div><span class="lO8SBd" tabindex="-1">.</span><div class="OSrXXb rbYSKb LfVVr" style="bottom:0px"><span>Jun 13, 2019</span></div></div></div></a>, <a class="WlydOe" data-jsarwt="1" data-usg="AOvVaw3V4XatJX6Tk37-dAp3LGee" data-ved="2ahUKEwiohMHu9oyEAxVbRjABHQvCCGkQxfQBKAB6BAgLEAE" href="https://www.theguardian.com/business/2019/jun/12/mobil-tax-exempt-donations-promote-interests-environmental-regulation-documents" jsname="YKoRaf"><div class="lSfe4c r5bEn aI5QMe"><div class="gpjNTe"><div class="YEMaTe JFSfwc" style="background-color:#3933da;height:92px;width:92px"><div class="uhHOwf BYbUcd" style="height:92px;width:92px"><img alt="" data-deferred="1" id="dimg_15" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///////yH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="/></div></div></div><div class="SoAPf"><div class="MgUUmf NUnG9d"><g-img class="QyR1Ze ZGomKf" style="margin-right:8px"><img alt="" class="YQ4gaf zr758c" data-deferred="1" height="16" id="dimg_21" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///////yH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" style="border-radius:2px 2px 2px 2px" width="16"/></g-img><span>The Guardian</span></div><div aria-level="3" class="n0jPhd ynAwRc MBeuO jBgGLd OSrXXb" role="heading">Revealed: Mobil sought to fight environmental regulation, documents <br/>show</div><div class="GI74Re jBgGLd OSrXXb" style="margin-top:8px">Revealed: documents from the early 1990s show oil giant looked to make
tax-<br/>exempt donations to promote the company's interests.</div><span class="lO8SBd" tabindex="-1">.</span><div class="OSrXXb rbYSKb LfVVr" style="bottom:0px"><span>Jun 12, 2019</span></div></div></div></a>, <a class="WlydOe" data-jsarwt="1" data-usg="AOvVaw2rn7Y-TfcnZGQxuzfseenC" data-ved="2ahUKEwiohMHu9oyEAxVbRjABHQvCCGkQxfQBKAB6BAgJEAE" href="https://www.hartenergy.com/exclusives/exxon-mobil-pursues-expansion-argentinas-vaca-muerta-shale-180621" jsname="YKoRaf"><div class="lSfe4c r5bEn aI5QMe"><div class="gpjNTe"><div class="YEMaTe JFSfwc" style="background-color:#f8f9fa;height:92px;width:92px"><div class="uhHOwf BYbUcd" style="height:92px;width:92px"><img alt="" data-deferred="1" id="dimg_6" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///////yH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="/></div></div></div><div class="SoAPf"><div class="MgUUmf NUnG9d"><g-img class="QyR1Ze ZGomKf" style="margin-right:8px"><img alt="" class="YQ4gaf zr758c" data-deferred="1" height="16" id="dimg_25" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///////yH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" style="border-radius:2px 2px 2px 2px" width="16"/></g-img><span>Hart Energy</span></div><div aria-level="3" class="n0jPhd ynAwRc MBeuO jBgGLd OSrXXb" role="heading">Exxon Mobil Pursues Expansion In Argentina's Vaca Muerta Shale</div><div class="GI74Re jBgGLd OSrXXb" style="margin-top:8px">Exxon Mobil plans to produce up to 55000 barrels of oil equivalent per day
within <br/>five years as part of the project.</div><span class="lO8SBd" tabindex="-1">.</span><div class="OSrXXb rbYSKb LfVVr" style="bottom:0px"><span>Jun 11, 2019</span></div></div></div></a>]

c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\pip_system_certs\wrapt_requests.py:71: UserWarning: Failed to patch SSL settings for unverified requests (unsupported version of urllib3?)
This may lead to errors when urllib3 tries to modify verify_mode.
Please report an issue at https://gitlab.com/alelec/pip-system-certs with your
python version included in the description

  warnings.warn(
c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '104.16.105.2'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\transformers\pipelines\text_classification.py:104: UserWarning: `return_all_scores` is now deprecated,  if want a similar functionality use `top_k=None` instead of `return_all_scores=True` or `top_k=1` instead of `return_all_scores=False`.
  warnings.warn(
Exception in thread Thread-22:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    p.prepare(
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 392, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/search?q=EXXON+MOBIL-XOM-NEWS&lr=lang_en&safe=active&sca_esv=3cbe9f3cb5d0638a&hl=en&gl=en&biw=1920&bih=976&source=lnms&sa=X&ved=2ahUKEwiohMHu9oyEAxVbRjABHQvCCGkQ0pQJegQIBhAC': No scheme supplied. Perhaps you meant http:///search?q=EXXON+MOBIL-XOM-NEWS&lr=lang_en&safe=active&sca_esv=3cbe9f3cb5d0638a&hl=en&gl=en&biw=1920&bih=976&source=lnms&sa=X&ved=2ahUKEwiohMHu9oyEAxVbRjABHQvCCGkQ0pQJegQIBhAC?
Exception in thread Thread-23:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    p.prepare(
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 392, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?
Exception in thread Thread-24:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=EXXON+MOBIL-XOM-NEWS&lr=lang_en&safe=active&sca_esv=3cbe9f3cb5d0638a&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:06/01/2019,cd_max:07/01/2019&tbm=vid&source=lnms&sa=X&ved=2ahUKEwiohMHu9oyEAxVbRjABHQvCCGkQ0pQJegQIBhAG'
Exception in thread Thread-25:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=EXXON+MOBIL-XOM-NEWS&lr=lang_en&safe=active&sca_esv=3cbe9f3cb5d0638a&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:06/01/2019,cd_max:07/01/2019&tbm=isch&source=lnms&sa=X&ved=2ahUKEwiohMHu9oyEAxVbRjABHQvCCGkQ0pQJegQIBhAI'
Exception in thread Thread-26:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=EXXON+MOBIL-XOM-NEWS&lr=lang_en&safe=active&sca_esv=3cbe9f3cb5d0638a&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:06/01/2019,cd_max:07/01/2019,sbd:1&tbm=bks&source=lnms&sa=X&ved=2ahUKEwiohMHu9oyEAxVbRjABHQvCCGkQ0pQJegQIBhAK'
c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '203.24.108.179'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '203.24.108.179'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '137.110.161.153'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '51.68.207.81'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '173.192.21.89'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '104.18.254.76'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '104.16.105.2'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '104.18.254.76'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '121.129.127.209'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
100%|██████████| 1/1 [01:10<00:00, 70.20s/it]

-------------------------------
------ creando dataframe ------
-------------------------------

In [14]:
df

,company,Year,Month,Day,date,media,description,title,link,Text,word_count
0,EXXON MOBIL-XOM-NEWS,2019,7,1,2019/07/01,,,,https://finance.yahoo.com/news/w-t-offshore-ac...,wt offshore to acquire 200m gom assets from ex...,816
1,EXXON MOBIL-XOM-NEWS,2019,7,1,2019/07/01,,,,https://www.investopedia.com/news/why-amazon-m...,why amazon microsoft netflix pose a risk to st...,1500
2,EXXON MOBIL-XOM-NEWS,2019,7,1,2019/07/01,,,,https://www.investopedia.com/news/10-most-love...,10 mostloved stocks in etfs investing stocks b...,800
3,EXXON MOBIL-XOM-NEWS,2019,7,1,2019/07/01,,,,https://money.usnews.com/investing/stock-marke...,oil stocks offer compelling value for patient ...,1500
4,EXXON MOBIL-XOM-NEWS,2019,7,1,2019/07/01,,,,https://finance.yahoo.com/news/where-exxonmobi...,where will exxonmobil be in 5 years home mail ...,1056
5,EXXON MOBIL-XOM-NEWS,2019,7,1,2019/07/01,,,,https://www.theguardian.com/business/2019/jun/...,revealed mobil sought to fight environmental r...,1200
6,EXXON MOBIL-XOM-NEWS,2019,7,1,2019/07/01,,,,https://www.hartenergy.com/exclusives/exxon-mo...,exxon mobil pursues expansion in argentinas va...,800

In [17]:
final_df

,company,Year,Month,Day,date,media,description,title,link,Text,word_count
0,FREEPORT-MCMORAN-FCX-NEWS,2019,7,1,2019/07/01,,,,https://www.csrwire.com/press_releases/42118-f...,csrwire named to forbes americas best large em...,200

In [2]:
from datetime import datetime
import threading
import time

DELAY_REQUESTS = 0
DELAY_RUN = 0


class Scraper:

    def __init__(self, name, company_serch, fecha, periodo, type_time, result_queue):
        self.name = name
        self.company_serch = company_serch
        self.fecha = fecha
        self.periodo = periodo
        self.type_time = type_time
        self.result = []
        self.result_queue = result_queue
        
    def exec(self):
        st = time.time()
        ht = datetime.now().time().strftime("%H:%M:%S")
        threads = [threading.Thread(target=self.run, args=(param,)) for param in self.company_serch]
        for thread in threads:
            time.sleep(DELAY_RUN)
            thread.start()

        for thread in threads:
            thread.join()

        self.result_queue.put({"name": self.name,
                               "fecha": self.fecha,
                               "ht": ht,
                               "t": time.time() - st,
                               "result": self.result})
        return self.result

    def run(self, param):
        st = time.time()
        self.result.append({"param": param,
                            "t": time.time() - st,
                            "df": scrap.GoogleNews([param], self.fecha, self.periodo, type_time = self.type_time)})

In [3]:
import multiprocessing
import time
import concurrent.futures


MAX_PROCESSORS = 4
results = []

data = {
    "2019-07-01":
        ["EXXON MOBIL-XOM-NEWS", "LINDE-LIN-NEWS", "SHERWIN-WILLIAMS-SHW-NEWS", "AIR PRDS.& CHEMS.-APD-NEWS", "NEWMONT-NEM-NEWS", 
                 "FREEPORT-MCMORAN-FCX-NEWS"
         ],
    "2019-08-01":
        ["EXXON MOBIL-XOM-NEWS", "LINDE-LIN-NEWS", "SHERWIN-WILLIAMS-SHW-NEWS", "AIR PRDS.& CHEMS.-APD-NEWS", "NEWMONT-NEM-NEWS", 
                 "FREEPORT-MCMORAN-FCX-NEWS"
         ],
    "2019-09-01":
        ["EXXON MOBIL-XOM-NEWS", "LINDE-LIN-NEWS", "SHERWIN-WILLIAMS-SHW-NEWS", "AIR PRDS.& CHEMS.-APD-NEWS", "NEWMONT-NEM-NEWS", 
                 "FREEPORT-MCMORAN-FCX-NEWS"],
    "2019-10-01":
        ["EXXON MOBIL-XOM-NEWS", "LINDE-LIN-NEWS", "SHERWIN-WILLIAMS-SHW-NEWS", "AIR PRDS.& CHEMS.-APD-NEWS", "NEWMONT-NEM-NEWS", 
                 "FREEPORT-MCMORAN-FCX-NEWS"],
    "2019-11-01":
        ["EXXON MOBIL-XOM-NEWS", "LINDE-LIN-NEWS", "SHERWIN-WILLIAMS-SHW-NEWS", "AIR PRDS.& CHEMS.-APD-NEWS", "NEWMONT-NEM-NEWS", 
                 "FREEPORT-MCMORAN-FCX-NEWS"]
}

if __name__ == "__main__":
    st = time.time()
    result_queue = multiprocessing.Queue()

    with concurrent.futures.ProcessPoolExecutor(MAX_PROCESSORS) as process_executor:
        with concurrent.futures.ThreadPoolExecutor(MAX_PROCESSORS) as thread_executor:
            futures = [thread_executor.submit(Scraper(f"ws{i}", params, fecha,  0, "MS", result_queue).exec)
                       for i, (fecha, params) in enumerate(data.items())]

            concurrent.futures.wait(futures)

    for _ in range(len(data)):
        result = result_queue.get()
        results.append(result)

07/01/2019
------------------------------------------------------------------
----------------------- Iniciando --------------------------------
------------------------------------------------------------------
Fecha de inicio: 07/01/2019
Fecha final: 07/01/2019
07/01/2019
------------------------------------------------------------------
----------------------- Iniciando --------------------------------
------------------------------------------------------------------
Fecha de inicio: 07/01/2019
Fecha final: 07/01/2019
07/01/2019
------------------------------------------------------------------
----------------------- Iniciando --------------------------------
------------------------------------------------------------------
Fecha de inicio: 07/01/2019
Fecha final: 07/01/2019
08/01/2019
------------------------------------------------------------------
----------------------- Iniciando --------------------------------
------------------------------------------------------------------
Fecha de inicio: 08/01/2019
Fecha final: 08/01/2019
09/01/2019
------------------------------------------------------------------
----------------------- Iniciando --------------------------------
------------------------------------------------------------------
Fecha de inicio: 09/01/2019
Fecha final: 09/01/2019
07/01/2019
------------------------------------------------------------------
----------------------- Iniciando --------------------------------
------------------------------------------------------------------
Fecha de inicio: 07/01/2019
Fecha final: 07/01/2019
08/01/2019
------------------------------------------------------------------
----------------------- Iniciando --------------------------------
------------------------------------------------------------------
Fecha de inicio: 08/01/2019
Fecha final: 08/01/2019
10/01/2019
------------------------------------------------------------------
----------------------- Iniciando --------------------------------
------------------------------------------------------------------
Fecha de inicio: 10/01/2019
Fecha final: 10/01/2019
09/01/2019
------------------------------------------------------------------
----------------------- Iniciando --------------------------------
------------------------------------------------------------------
Fecha de inicio: 09/01/2019
Fecha final: 09/01/2019
08/01/2019
------------------------------------------------------------------
----------------------- Iniciando --------------------------------
------------------------------------------------------------------
Fecha de inicio: 08/01/2019
Fecha final: 08/01/2019
10/01/2019
------------------------------------------------------------------
----------------------- Iniciando --------------------------------
------------------------------------------------------------------
Fecha de inicio: 10/01/2019
Fecha final: 10/01/2019
07/01/2019
------------------------------------------------------------------
----------------------- Iniciando --------------------------------
------------------------------------------------------------------
Fecha de inicio: 07/01/2019
Fecha final: 07/01/2019
09/01/2019
------------------------------------------------------------------
----------------------- Iniciando --------------------------------
------------------------------------------------------------------
Fecha de inicio: 09/01/2019
Fecha final: 09/01/2019
10/01/2019
------------------------------------------------------------------
----------------------- Iniciando --------------------------------
------------------------------------------------------------------
Fecha de inicio: 10/01/2019
Fecha final: 10/01/2019
09/01/2019
------------------------------------------------------------------
----------------------- Iniciando --------------------------------
------------------------------------------------------------------
Fecha de inicio: 09/01/2019
Fecha final: 09/01/2019
07/01/2019
------------------------------------------------------------------
----------------------- Iniciando --------------------------------
------------------------------------------------------------------
Fecha de inicio: 07/01/2019
Fecha final: 07/01/2019
09/01/2019
------------------------------------------------------------------
----------------------- Iniciando --------------------------------
------------------------------------------------------------------
Fecha de inicio: 09/01/2019
Fecha final: 09/01/2019
08/01/2019
------------------------------------------------------------------
----------------------- Iniciando --------------------------------
------------------------------------------------------------------
Fecha de inicio: 08/01/2019
Fecha final: 08/01/2019
10/01/2019
------------------------------------------------------------------
----------------------- Iniciando --------------------------------
------------------------------------------------------------------
Fecha de inicio: 10/01/2019
Fecha final: 10/01/2019
08/01/2019
------------------------------------------------------------------
----------------------- Iniciando --------------------------------
------------------------------------------------------------------
Fecha de inicio: 08/01/2019
Fecha final: 08/01/2019
09/01/2019
------------------------------------------------------------------
----------------------- Iniciando --------------------------------
------------------------------------------------------------------
Fecha de inicio: 09/01/2019
Fecha final: 09/01/2019
10/01/2019
------------------------------------------------------------------
----------------------- Iniciando --------------------------------
------------------------------------------------------------------
Fecha de inicio: 10/01/2019
Fecha final: 10/01/2019
08/01/2019
------------------------------------------------------------------
----------------------- Iniciando --------------------------------
------------------------------------------------------------------
Fecha de inicio: 08/01/2019
Fecha final: 08/01/2019

10/01/2019
------------------------------------------------------------------
----------------------- Iniciando --------------------------------
------------------------------------------------------------------
Fecha de inicio: 10/01/2019
Fecha final: 10/01/2019

  0%|          | 0/1 [00:00<?, ?it/s]

-----------------------nueva version--------------------
https://www.google.com/search?q=SHERWIN-WILLIAMS-SHW-NEWS&lr=lang_en&biw=1920&bih=976&source=lnt&&tbs=lr:lang_1en,cdr:1,cd_min:07/01/2019,cd_max:07/01/2019,sbd:1&tbm=nws&start=0
-----------------------nueva version--------------------
https://www.google.com/search?q=EXXON%20MOBIL-XOM-NEWS&lr=lang_en&biw=1920&bih=976&source=lnt&&tbs=lr:lang_1en,cdr:1,cd_min:07/01/2019,cd_max:07/01/2019,sbd:1&tbm=nws&start=0
-----------------------nueva version--------------------
https://www.google.com/search?q=LINDE-LIN-NEWS&lr=lang_en&biw=1920&bih=976&source=lnt&&tbs=lr:lang_1en,cdr:1,cd_min:07/01/2019,cd_max:07/01/2019,sbd:1&tbm=nws&start=0
-----------------------nueva version--------------------
https://www.google.com/search?q=EXXON%20MOBIL-XOM-NEWS&lr=lang_en&biw=1920&bih=976&source=lnt&&tbs=lr:lang_1en,cdr:1,cd_min:08/01/2019,cd_max:08/01/2019,sbd:1&tbm=nws&start=0
-----------------------nueva version--------------------
https://www.google.com/search?q=AIR%20PRDS.%26%20CHEMS.-APD-NEWS&lr=lang_en&biw=1920&bih=976&source=lnt&&tbs=lr:lang_1en,cdr:1,cd_min:07/01/2019,cd_max:07/01/2019,sbd:1&tbm=nws&start=0
-----------------------nueva version--------------------
https://www.google.com/search?q=EXXON%20MOBIL-XOM-NEWS&lr=lang_en&biw=1920&bih=976&source=lnt&&tbs=lr:lang_1en,cdr:1,cd_min:09/01/2019,cd_max:09/01/2019,sbd:1&tbm=nws&start=0
-----------------------nueva version--------------------
https://www.google.com/search?q=LINDE-LIN-NEWS&lr=lang_en&biw=1920&bih=976&source=lnt&&tbs=lr:lang_1en,cdr:1,cd_min:08/01/2019,cd_max:08/01/2019,sbd:1&tbm=nws&start=0
-----------------------nueva version--------------------
https://www.google.com/search?q=EXXON%20MOBIL-XOM-NEWS&lr=lang_en&biw=1920&bih=976&source=lnt&&tbs=lr:lang_1en,cdr:1,cd_min:10/01/2019,cd_max:10/01/2019,sbd:1&tbm=nws&start=0

-----------------------nueva version--------------------
https://www.google.com/search?q=LINDE-LIN-NEWS&lr=lang_en&biw=1920&bih=976&source=lnt&&tbs=lr:lang_1en,cdr:1,cd_min:09/01/2019,cd_max:09/01/2019,sbd:1&tbm=nws&start=0

-----------------------nueva version--------------------
https://www.google.com/search?q=AIR%20PRDS.%26%20CHEMS.-APD-NEWS&lr=lang_en&biw=1920&bih=976&source=lnt&&tbs=lr:lang_1en,cdr:1,cd_min:09/01/2019,cd_max:09/01/2019,sbd:1&tbm=nws&start=0
-----------------------nueva version--------------------
https://www.google.com/search?q=SHERWIN-WILLIAMS-SHW-NEWS&lr=lang_en&biw=1920&bih=976&source=lnt&&tbs=lr:lang_1en,cdr:1,cd_min:09/01/2019,cd_max:09/01/2019,sbd:1&tbm=nws&start=0

  0%|          | 0/1 [00:00<?, ?it/s]

-----------------------nueva version--------------------
https://www.google.com/search?q=SHERWIN-WILLIAMS-SHW-NEWS&lr=lang_en&biw=1920&bih=976&source=lnt&&tbs=lr:lang_1en,cdr:1,cd_min:08/01/2019,cd_max:08/01/2019,sbd:1&tbm=nws&start=0
-----------------------nueva version--------------------
https://www.google.com/search?q=SHERWIN-WILLIAMS-SHW-NEWS&lr=lang_en&biw=1920&bih=976&source=lnt&&tbs=lr:lang_1en,cdr:1,cd_min:10/01/2019,cd_max:10/01/2019,sbd:1&tbm=nws&start=0
-----------------------nueva version--------------------
https://www.google.com/search?q=FREEPORT-MCMORAN-FCX-NEWS&lr=lang_en&biw=1920&bih=976&source=lnt&&tbs=lr:lang_1en,cdr:1,cd_min:07/01/2019,cd_max:07/01/2019,sbd:1&tbm=nws&start=0
-----------------------nueva version--------------------
https://www.google.com/search?q=NEWMONT-NEM-NEWS&lr=lang_en&biw=1920&bih=976&source=lnt&&tbs=lr:lang_1en,cdr:1,cd_min:09/01/2019,cd_max:09/01/2019,sbd:1&tbm=nws&start=0
-----------------------nueva version--------------------
https://www.google.com/search?q=LINDE-LIN-NEWS&lr=lang_en&biw=1920&bih=976&source=lnt&&tbs=lr:lang_1en,cdr:1,cd_min:10/01/2019,cd_max:10/01/2019,sbd:1&tbm=nws&start=0
-----------------------nueva version--------------------
https://www.google.com/search?q=NEWMONT-NEM-NEWS&lr=lang_en&biw=1920&bih=976&source=lnt&&tbs=lr:lang_1en,cdr:1,cd_min:07/01/2019,cd_max:07/01/2019,sbd:1&tbm=nws&start=0
-----------------------nueva version--------------------
https://www.google.com/search?q=AIR%20PRDS.%26%20CHEMS.-APD-NEWS&lr=lang_en&biw=1920&bih=976&source=lnt&&tbs=lr:lang_1en,cdr:1,cd_min:08/01/2019,cd_max:08/01/2019,sbd:1&tbm=nws&start=0

-----------------------nueva version--------------------
https://www.google.com/search?q=AIR%20PRDS.%26%20CHEMS.-APD-NEWS&lr=lang_en&biw=1920&bih=976&source=lnt&&tbs=lr:lang_1en,cdr:1,cd_min:10/01/2019,cd_max:10/01/2019,sbd:1&tbm=nws&start=0
-----------------------nueva version--------------------
https://www.google.com/search?q=NEWMONT-NEM-NEWS&lr=lang_en&biw=1920&bih=976&source=lnt&&tbs=lr:lang_1en,cdr:1,cd_min:08/01/2019,cd_max:08/01/2019,sbd:1&tbm=nws&start=0
-----------------------nueva version--------------------
https://www.google.com/search?q=FREEPORT-MCMORAN-FCX-NEWS&lr=lang_en&biw=1920&bih=976&source=lnt&&tbs=lr:lang_1en,cdr:1,cd_min:10/01/2019,cd_max:10/01/2019,sbd:1&tbm=nws&start=0
-----------------------nueva version--------------------
https://www.google.com/search?q=FREEPORT-MCMORAN-FCX-NEWS&lr=lang_en&biw=1920&bih=976&source=lnt&&tbs=lr:lang_1en,cdr:1,cd_min:09/01/2019,cd_max:09/01/2019,sbd:1&tbm=nws&start=0
-----------------------nueva version--------------------
https://www.google.com/search?q=NEWMONT-NEM-NEWS&lr=lang_en&biw=1920&bih=976&source=lnt&&tbs=lr:lang_1en,cdr:1,cd_min:10/01/2019,cd_max:10/01/2019,sbd:1&tbm=nws&start=0
-----------------------nueva version--------------------
https://www.google.com/search?q=FREEPORT-MCMORAN-FCX-NEWS&lr=lang_en&biw=1920&bih=976&source=lnt&&tbs=lr:lang_1en,cdr:1,cd_min:08/01/2019,cd_max:08/01/2019,sbd:1&tbm=nws&start=0

Exception in thread Thread-30:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
Exception in thread Thread-31:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
Exception in thread Thread-33:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
Exception in thread Thread-32:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
Exception in thread Thread-37:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
Exception in thread Thread-35:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
Exception in thread Thread-34:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
Exception in thread Thread-39:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
Exception in thread Thread-36:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
Exception in thread Thread-43:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
Exception in thread Thread-38:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
Exception in thread Thread-42:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    p.prepare(
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 318, in prepare
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
Exception in thread Thread-40:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
Exception in thread Thread-50:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
Exception in thread Thread-48:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    self.prepare_url(url, params)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 392, in prepare_url
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    p.prepare(
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 318, in prepare
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
Exception in thread Thread-49:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.prepare_url(url, params)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 392, in prepare_url
    p.prepare(
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 318, in prepare
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    self.prepare_url(url, params)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 392, in prepare_url
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
Exception in thread Thread-44:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
Exception in thread Thread-51:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?
        return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    p.prepare(
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 318, in prepare
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
Exception in thread Thread-46:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?
Exception in thread Thread-47:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    self.prepare_url(url, params)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 392, in prepare_url
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    p.prepare(
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 318, in prepare
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
Exception in thread Thread-41:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    p.prepare(
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 318, in prepare
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?
Exception in thread Thread-45:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
        self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    p.prepare(
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 318, in prepare
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    p.prepare(
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 318, in prepare
Exception in thread Thread-52:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.prepare_url(url, params)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 392, in prepare_url
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    p.prepare(
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 318, in prepare
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?
    self.prepare_url(url, params)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 392, in prepare_url
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})

-------------------------------
------ creando dataframe ------
-------------------------------

Exception in thread Thread-123:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    p.prepare(
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 318, in prepare
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    self.prepare_url(url, params)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 392, in prepare_url
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=EXXON+MOBIL-XOM-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:10/01/2019,cd_max:10/01/2019&tbm=isch&source=lnms&sa=X&ved=2ahUKEwiagujYr8yEAxUjia8BHYmFBwgQ0pQJegQIBhAI'
Exception in thread Thread-125:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
Exception in thread Thread-124:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=LINDE-LIN-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:07/01/2019,cd_max:07/01/2019&tbm=vid&source=lnms&sa=X&ved=2ahUKEwjKpOLYr8yEAxVwiK8BHc9EDUcQ0pQJegQIBhAI'
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=NEWMONT-NEM-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&sca_upv=1&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:09/01/2019,cd_max:09/01/2019&tbm=vid&source=lnms&sa=X&ved=2ahUKEwiB5O7Yr8yEAxX5kq8BHVAbBzoQ0pQJegQIBhAG'
Exception in thread Thread-126:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
Exception in thread Thread-127:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
    p.prepare(
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 392, in prepare_url
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?
    p.prepare(
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 392, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?
Exception in thread Thread-129:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
Exception in thread Thread-128:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
Exception in thread Thread-130:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    p.prepare(
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 318, in prepare
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    self.prepare_url(url, params)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 392, in prepare_url
    p.prepare(
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 318, in prepare
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=LINDE-LIN-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&sca_upv=1&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:10/01/2019,cd_max:10/01/2019&tbm=isch&source=lnms&sa=X&ved=2ahUKEwi-j-_Yr8yEAxU6UPUHHY4YAzIQ0pQJegQIBhAG'
    self.prepare_url(url, params)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 392, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?
Exception in thread Thread-131:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    Exception in thread Thread-132:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    p.prepare(
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 318, in prepare
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    self.prepare_url(url, params)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 392, in prepare_url
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=AIR+PRDS.%26+CHEMS.-APD-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:10/01/2019,cd_max:10/01/2019&tbm=vid&source=lnms&sa=X&ved=2ahUKEwjKyPTYr8yEAxX8j68BHShXC-YQ0pQJegQIBhAG'
Exception in thread Thread-133:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=FREEPORT-MCMORAN-FCX-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:07/01/2019,cd_max:07/01/2019&tbm=vid&source=lnms&sa=X&ved=2ahUKEwiFg-3Yr8yEAxWyfvUHHREuD4EQ0pQJegQIBhAG'
Exception in thread Thread-134:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=FREEPORT-MCMORAN-FCX-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:10/01/2019,cd_max:10/01/2019&tbm=vid&source=lnms&sa=X&ved=2ahUKEwjDtfbYr8yEAxWKlK8BHWI0BAgQ0pQJegQIBhAG'
c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '173.192.21.89'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
Exception in thread Thread-136:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
Exception in thread Thread-137:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})

-------------------------------
------ creando dataframe ------
-------------------------------

Exception in thread Thread-168:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
Exception in thread Thread-169:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=FREEPORT-MCMORAN-FCX-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:09/01/2019,cd_max:09/01/2019&tbm=isch&source=lnms&sa=X&ved=2ahUKEwiei_fYr8yEAxXZkq8BHTrUCEEQ0pQJegQIBhAK'
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=EXXON+MOBIL-XOM-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:07/01/2019,cd_max:07/01/2019&tbm=isch&source=lnms&sa=X&ved=2ahUKEwjep-LYr8yEAxWdgq8BHZ-rDWgQ0pQJegQIBhAI'
Exception in thread Thread-170:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=FREEPORT-MCMORAN-FCX-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:08/01/2019,cd_max:08/01/2019,sbd:1&tbm=bks&source=lnms&sa=X&ved=2ahUKEwiL-vrYr8yEAxUEkq8BHRNEBMoQ0pQJegQIBhAI'
Exception in thread Thread-171:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=NEWMONT-NEM-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:07/01/2019,cd_max:07/01/2019,sbd:1&tbm=bks&source=lnms&sa=X&ved=2ahUKEwjJzvDYr8yEAxW5h68BHbfwBmkQ0pQJegQIBhAK'
Exception in thread Thread-172:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=NEWMONT-NEM-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&sca_upv=1&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:09/01/2019,cd_max:09/01/2019,sbd:1&tbm=bks&source=lnms&sa=X&ved=2ahUKEwiB5O7Yr8yEAxX5kq8BHVAbBzoQ0pQJegQIBhAK'
Exception in thread Thread-173:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=LINDE-LIN-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&sca_upv=1&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:09/01/2019,cd_max:09/01/2019&tbm=vid&source=lnms&sa=X&ved=2ahUKEwjxwOnYr8yEAxU1nK8BHVM5AxkQ0pQJegQIBhAI'
Exception in thread Thread-174:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=FREEPORT-MCMORAN-FCX-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:10/01/2019,cd_max:10/01/2019&tbm=isch&source=lnms&sa=X&ved=2ahUKEwjDtfbYr8yEAxWKlK8BHWI0BAgQ0pQJegQIBhAK'
Exception in thread Thread-176:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=AIR+PRDS.%26+CHEMS.-APD-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:09/01/2019,cd_max:09/01/2019&tbm=isch&source=lnms&sa=X&ved=2ahUKEwiRuInZr8yEAxUBdPUHHYHWCCEQ0pQJegQIBhAI'
c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '104.16.241.204'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(




100%|██████████| 1/1 [00:28<00:00, 28.84s/it]


















100%|██████████| 1/1 [00:28<00:00, 28.73s/it]

-------------------------------
------ creando dataframe ------
-------------------------------

Exception in thread Thread-177:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
100%|██████████| 1/1 [00:28<00:00, 28.80s/it]
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=AIR+PRDS.%26+CHEMS.-APD-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:08/01/2019,cd_max:08/01/2019,sbd:1&tbm=bks&source=lnms&sa=X&ved=2ahUKEwipofPYr8yEAxXwevUHHcCKAWQQ0pQJegQIBhAK'
Exception in thread Thread-178:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=FREEPORT-MCMORAN-FCX-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:07/01/2019,cd_max:07/01/2019&tbm=isch&source=lnms&sa=X&ved=2ahUKEwiFg-3Yr8yEAxWyfvUHHREuD4EQ0pQJegQIBhAK'

-------------------------------
------ creando dataframe ------
-------------------------------

Exception in thread Thread-179:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
Exception in thread Thread-180:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=AIR+PRDS.%26+CHEMS.-APD-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:09/01/2019,cd_max:09/01/2019,sbd:1&tbm=bks&source=lnms&sa=X&ved=2ahUKEwiRuInZr8yEAxUBdPUHHYHWCCEQ0pQJegQIBhAK'
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=SHERWIN-WILLIAMS-SHW-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:07/01/2019,cd_max:07/01/2019&tbm=vid&source=lnms&sa=X&ved=2ahUKEwifmuHYr8yEAxUBhq8BHWgOCFEQ0pQJegQIBRAI'




Exception in thread Thread-182:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '31.220.54.116'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
Exception in thread Thread-183:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
100%|██████████| 1/1 [00:30<00:00, 30.12s/it]    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
100%|██████████| 1/1 [00:30<00:00, 30.24s/it]    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get

    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=NEWMONT-NEM-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:08/01/2019,cd_max:08/01/2019&tbm=isch&source=lnms&sa=X&ved=2ahUKEwif7_rYr8yEAxXkka8BHeRDAeYQ0pQJegQIBhAI'
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=SHERWIN-WILLIAMS-SHW-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:09/01/2019,cd_max:09/01/2019&tbm=vid&source=lnms&sa=X&ved=2ahUKEwiQrerYr8yEAxVnafUHHaM6DHwQ0pQJegQIBhAI'
c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '173.192.21.89'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

-------------------------------
------ creando dataframe ------
-------------------------------

Exception in thread Thread-185:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=EXXON+MOBIL-XOM-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:08/01/2019,cd_max:08/01/2019,sbd:1&tbm=bks&source=lnms&sa=X&ved=2ahUKEwjp-OLYr8yEAxVBlK8BHYoeCbQQ0pQJegQIBhAK'
Exception in thread Thread-186:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=LINDE-LIN-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:08/01/2019,cd_max:08/01/2019&tbm=vid&source=lnms&sa=X&ved=2ahUKEwi_1ubYr8yEAxX-kq8BHSMqBAYQ0pQJegQIBhAI'
c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '173.192.21.89'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
















100%|██████████| 1/1 [00:30<00:00, 30.83s/it]

-------------------------------
------ creando dataframe ------
-------------------------------

100%|██████████| 1/1 [00:31<00:00, 31.10s/it]
c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '51.68.207.81'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

-------------------------------
------ creando dataframe ------
-------------------------------

c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '101.231.66.130'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
Exception in thread Thread-190:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=SHERWIN-WILLIAMS-SHW-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:10/01/2019,cd_max:10/01/2019&tbm=vid&source=lnms&sa=X&ved=2ahUKEwjf-uvYr8yEAxXrm68BHZluBFwQ0pQJegQIBRAI'

c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '173.192.21.89'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
Exception in thread Thread-191:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
100%|██████████| 1/1 [00:32<00:00, 32.39s/it]
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=EXXON+MOBIL-XOM-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:07/01/2019,cd_max:07/01/2019,sbd:1&tbm=bks&source=lnms&sa=X&ved=2ahUKEwjep-LYr8yEAxWdgq8BHZ-rDWgQ0pQJegQIBhAK'
Exception in thread Thread-192:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=FREEPORT-MCMORAN-FCX-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:08/01/2019,cd_max:08/01/2019&tbm=isch&source=lnms&sa=X&ved=2ahUKEwiL-vrYr8yEAxUEkq8BHRNEBMoQ0pQJegQIBhAK'

-------------------------------
------ creando dataframe ------
-------------------------------

100%|██████████| 1/1 [00:32<00:00, 32.90s/it]
c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '51.68.207.81'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
Exception in thread Thread-193:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=NEWMONT-NEM-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:08/01/2019,cd_max:08/01/2019,sbd:1&tbm=bks&source=lnms&sa=X&ved=2ahUKEwif7_rYr8yEAxXkka8BHeRDAeYQ0pQJegQIBhAK'

-------------------------------
------ creando dataframe ------
-------------------------------

c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '101.231.66.130'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '137.110.161.153'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '104.16.105.2'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(














100%|██████████| 1/1 [00:34<00:00, 34.46s/it]c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '104.18.254.76'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
100%|██████████| 1/1 [00:34<00:00, 34.53s/it]A
100%|██████████| 1/1 [00:34<00:00, 34.71s/it]
c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '104.18.254.76'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

-------------------------------
------ creando dataframe ------
-------------------------------
-------------------------------
------ creando dataframe ------
-------------------------------

c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '51.68.207.81'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

100%|██████████| 1/1 [00:35<00:00, 35.54s/it]
c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '137.110.161.153'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

-------------------------------
------ creando dataframe ------
-------------------------------

c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '31.220.54.116'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(




100%|██████████| 1/1 [00:36<00:00, 36.10s/it]
c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '104.18.254.76'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

-------------------------------
------ creando dataframe ------
-------------------------------

100%|██████████| 1/1 [00:36<00:00, 36.45s/it]

-------------------------------
------ creando dataframe ------
-------------------------------

100%|██████████| 1/1 [00:36<00:00, 36.95s/it]

-------------------------------
------ creando dataframe ------
-------------------------------

100%|██████████| 1/1 [00:37<00:00, 37.56s/it]

-------------------------------
------ creando dataframe ------
-------------------------------

c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '31.220.54.116'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(


100%|██████████| 1/1 [00:38<00:00, 38.15s/it]

-------------------------------
------ creando dataframe ------
-------------------------------

100%|██████████| 1/1 [00:38<00:00, 38.40s/it]






100%|██████████| 1/1 [00:38<00:00, 38.53s/it]

-------------------------------
------ creando dataframe ------
-------------------------------
-------------------------------
------ creando dataframe ------
-------------------------------

100%|██████████| 1/1 [00:39<00:00, 39.38s/it]

-------------------------------
------ creando dataframe ------
-------------------------------
11/01/2019
------------------------------------------------------------------
----------------------- Iniciando --------------------------------
------------------------------------------------------------------
Fecha de inicio: 11/01/2019
Fecha final: 11/01/2019
11/01/2019
------------------------------------------------------------------
----------------------- Iniciando --------------------------------
------------------------------------------------------------------
Fecha de inicio: 11/01/2019
Fecha final: 11/01/2019
11/01/2019
------------------------------------------------------------------
----------------------- Iniciando --------------------------------
------------------------------------------------------------------
Fecha de inicio: 11/01/2019
Fecha final: 11/01/2019
11/01/2019
------------------------------------------------------------------
----------------------- Iniciando --------------------------------
------------------------------------------------------------------
Fecha de inicio: 11/01/2019
Fecha final: 11/01/2019

  0%|          | 0/1 [00:00<?, ?it/s]

11/01/2019
------------------------------------------------------------------
----------------------- Iniciando --------------------------------
------------------------------------------------------------------
Fecha de inicio: 11/01/2019
Fecha final: 11/01/2019
11/01/2019
------------------------------------------------------------------
----------------------- Iniciando --------------------------------
------------------------------------------------------------------
Fecha de inicio: 11/01/2019
Fecha final: 11/01/2019

-----------------------nueva version--------------------
https://www.google.com/search?q=EXXON%20MOBIL-XOM-NEWS&lr=lang_en&biw=1920&bih=976&source=lnt&&tbs=lr:lang_1en,cdr:1,cd_min:11/01/2019,cd_max:11/01/2019,sbd:1&tbm=nws&start=0

  0%|          | 0/1 [00:00<?, ?it/s]

-----------------------nueva version--------------------
https://www.google.com/search?q=SHERWIN-WILLIAMS-SHW-NEWS&lr=lang_en&biw=1920&bih=976&source=lnt&&tbs=lr:lang_1en,cdr:1,cd_min:11/01/2019,cd_max:11/01/2019,sbd:1&tbm=nws&start=0
-----------------------nueva version--------------------
https://www.google.com/search?q=LINDE-LIN-NEWS&lr=lang_en&biw=1920&bih=976&source=lnt&&tbs=lr:lang_1en,cdr:1,cd_min:11/01/2019,cd_max:11/01/2019,sbd:1&tbm=nws&start=0
-----------------------nueva version--------------------
https://www.google.com/search?q=AIR%20PRDS.%26%20CHEMS.-APD-NEWS&lr=lang_en&biw=1920&bih=976&source=lnt&&tbs=lr:lang_1en,cdr:1,cd_min:11/01/2019,cd_max:11/01/2019,sbd:1&tbm=nws&start=0

-----------------------nueva version--------------------
https://www.google.com/search?q=NEWMONT-NEM-NEWS&lr=lang_en&biw=1920&bih=976&source=lnt&&tbs=lr:lang_1en,cdr:1,cd_min:11/01/2019,cd_max:11/01/2019,sbd:1&tbm=nws&start=0
-----------------------nueva version--------------------
https://www.google.com/search?q=FREEPORT-MCMORAN-FCX-NEWS&lr=lang_en&biw=1920&bih=976&source=lnt&&tbs=lr:lang_1en,cdr:1,cd_min:11/01/2019,cd_max:11/01/2019,sbd:1&tbm=nws&start=0

100%|██████████| 1/1 [00:39<00:00, 39.62s/it]

-------------------------------
------ creando dataframe ------
-------------------------------

Exception in thread Thread-209:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
Exception in thread Thread-208:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
Exception in thread Thread-206:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner













Exception in thread Thread-207:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
100%|██████████| 1/1 [00:40<00:00, 40.58s/it]        self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
100%|██████████| 1/1 [00:40<00:00, 40.65s/it]Exception in thread Thread-210:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get

    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    p.prepare(
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 318, in prepare
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
    self.prepare_url(url, params)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 392, in prepare_url
    p.prepare(
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 318, in prepare
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    p.prepare(
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 318, in prepare
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?
    p.prepare(
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 392, in prepare_url
    p.prepare(
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 392, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?
    self.prepare_url(url, params)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 392, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?
    self.prepare_url(url, params)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 392, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?

-------------------------------
------ creando dataframe ------
-------------------------------

Exception in thread Thread-211:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    p.prepare(
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 392, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?
c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '137.110.161.153'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '31.220.54.116'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '101.231.66.130'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '31.220.54.116'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '51.68.207.81'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '101.231.66.130'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '31.220.54.116'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
Exception in thread Thread-218:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    p.prepare(
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 392, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/search?q=NEWMONT-NEM-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&source=lnms&sa=X&ved=2ahUKEwj51NDrr8yEAxVYiq8BHURQAxYQ0pQJegQIBhAC': No scheme supplied. Perhaps you meant http:///search?q=NEWMONT-NEM-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&source=lnms&sa=X&ved=2ahUKEwj51NDrr8yEAxVYiq8BHURQAxYQ0pQJegQIBhAC?















Exception in thread Thread-219:
Traceback (most recent call last):
100%|██████████| 1/1 [00:45<00:00, 45.40s/it]50, in _bootstrap_inner    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run

    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    p.prepare(
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 392, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/search?q=LINDE-LIN-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&source=lnms&sa=X&ved=2ahUKEwjt8I3sr8yEAxXeavUHHYaFCG4Q0pQJegQIBhAC': No scheme supplied. Perhaps you meant http:///search?q=LINDE-LIN-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&source=lnms&sa=X&ved=2ahUKEwjt8I3sr8yEAxXeavUHHYaFCG4Q0pQJegQIBhAC?

-------------------------------
------ creando dataframe ------
-------------------------------

Exception in thread Thread-220:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    p.prepare(
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 392, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/search?q=SHERWIN-WILLIAMS-SHW-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&source=lnms&sa=X&ved=2ahUKEwid8M3rr8yEAxUdm68BHW20CZ0Q0pQJegQIBhAC': No scheme supplied. Perhaps you meant http:///search?q=SHERWIN-WILLIAMS-SHW-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&source=lnms&sa=X&ved=2ahUKEwid8M3rr8yEAxUdm68BHW20CZ0Q0pQJegQIBhAC?
Exception in thread Thread-221:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    p.prepare(
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 392, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?
c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '104.16.105.2'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
Exception in thread Thread-223:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    p.prepare(
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 392, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/search?q=AIR+PRDS.%26+CHEMS.-APD-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&source=lnms&sa=X&ved=2ahUKEwigq9Hrr8yEAxX8hq8BHRQdCTEQ0pQJegQIBhAC': No scheme supplied. Perhaps you meant http:///search?q=AIR+PRDS.%26+CHEMS.-APD-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&source=lnms&sa=X&ved=2ahUKEwigq9Hrr8yEAxX8hq8BHRQdCTEQ0pQJegQIBhAC?
Exception in thread Thread-224:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    p.prepare(
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 392, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/search?q=EXXON+MOBIL-XOM-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&source=lnms&sa=X&ved=2ahUKEwjOqc3rr8yEAxWTgK8BHSrbAiUQ0pQJegQIBhAC': No scheme supplied. Perhaps you meant http:///search?q=EXXON+MOBIL-XOM-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&source=lnms&sa=X&ved=2ahUKEwjOqc3rr8yEAxWTgK8BHSrbAiUQ0pQJegQIBhAC?
Exception in thread Thread-225:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    p.prepare(
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 392, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/search?q=FREEPORT-MCMORAN-FCX-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&source=lnms&sa=X&ved=2ahUKEwjGqdHrr8yEAxWhYfUHHUXBB_8Q0pQJegQIBhAC': No scheme supplied. Perhaps you meant http:///search?q=FREEPORT-MCMORAN-FCX-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&source=lnms&sa=X&ved=2ahUKEwjGqdHrr8yEAxWhYfUHHUXBB_8Q0pQJegQIBhAC?
Exception in thread Thread-226:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
Exception in thread Thread-227:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    p.prepare(
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 318, in prepare
    p.prepare(
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 392, in prepare_url
    self.prepare_url(url, params)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 392, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?











100%|██████████| 1/1 [00:50<00:00, 50.54s/it]

-------------------------------
------ creando dataframe ------
-------------------------------

Exception in thread Thread-228:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=LINDE-LIN-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:11/01/2019,cd_max:11/01/2019&tbm=isch&source=lnms&sa=X&ved=2ahUKEwjt8I3sr8yEAxXeavUHHYaFCG4Q0pQJegQIBhAG'
Exception in thread Thread-229:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    p.prepare(
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 392, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?
Exception in thread Thread-230:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    p.prepare(
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 392, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?
Exception in thread Thread-231:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 443, in prepare_request
    p.prepare(
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\models.py", line 392, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?
Exception in thread Thread-232:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=NEWMONT-NEM-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:11/01/2019,cd_max:11/01/2019&tbm=vid&source=lnms&sa=X&ved=2ahUKEwj51NDrr8yEAxVYiq8BHURQAxYQ0pQJegQIBhAG'
Exception in thread Thread-233:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=FREEPORT-MCMORAN-FCX-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:11/01/2019,cd_max:11/01/2019&tbm=vid&source=lnms&sa=X&ved=2ahUKEwjGqdHrr8yEAxWhYfUHHUXBB_8Q0pQJegQIBhAG'
Exception in thread Thread-234:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=EXXON+MOBIL-XOM-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:11/01/2019,cd_max:11/01/2019&tbm=vid&source=lnms&sa=X&ved=2ahUKEwjOqc3rr8yEAxWTgK8BHSrbAiUQ0pQJegQIBhAG'
Exception in thread Thread-235:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=SHERWIN-WILLIAMS-SHW-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:11/01/2019,cd_max:11/01/2019&tbm=isch&source=lnms&sa=X&ved=2ahUKEwid8M3rr8yEAxUdm68BHW20CZ0Q0pQJegQIBhAG'
Exception in thread Thread-236:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=NEWMONT-NEM-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:11/01/2019,cd_max:11/01/2019&tbm=isch&source=lnms&sa=X&ved=2ahUKEwj51NDrr8yEAxVYiq8BHURQAxYQ0pQJegQIBhAI'
Exception in thread Thread-237:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=LINDE-LIN-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:11/01/2019,cd_max:11/01/2019&tbm=vid&source=lnms&sa=X&ved=2ahUKEwjt8I3sr8yEAxXeavUHHYaFCG4Q0pQJegQIBhAI'
Exception in thread Thread-238:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=AIR+PRDS.%26+CHEMS.-APD-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:11/01/2019,cd_max:11/01/2019&tbm=vid&source=lnms&sa=X&ved=2ahUKEwigq9Hrr8yEAxX8hq8BHRQdCTEQ0pQJegQIBhAG'
Exception in thread Thread-239:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=FREEPORT-MCMORAN-FCX-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:11/01/2019,cd_max:11/01/2019,sbd:1&tbm=bks&source=lnms&sa=X&ved=2ahUKEwjGqdHrr8yEAxWhYfUHHUXBB_8Q0pQJegQIBhAI'
Exception in thread Thread-240:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
Exception in thread Thread-241:
Traceback (most recent call last):
  File "C:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)

-------------------------------
------ creando dataframe ------
-------------------------------

c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\urllib3\connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '104.16.241.204'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(




100%|██████████| 1/1 [00:23<00:00, 23.62s/it]

-------------------------------
------ creando dataframe ------
-------------------------------

Exception in thread Thread-249:
Traceback (most recent call last):
100%|██████████| 1/1 [00:26<00:00, 26.15s/it]50, in _bootstrap_inner    self.run()
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\src\scraping.py", line 117, in run

    response=req.get(self.url,headers=headers, proxies={"http": proxy, "https": proxy})
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 639, in send
    adapter = self.get_adapter(url=request.url)
  File "c:\Users\jormora\Documents\GitHub\vitd-scraping\scraping\lib\site-packages\requests\sessions.py", line 732, in get_adapter
    raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for '/search?q=AIR+PRDS.%26+CHEMS.-APD-NEWS&lr=lang_en&safe=active&sca_esv=bc4b5e46aeab13ae&hl=en&gl=en&biw=1920&bih=976&tbs=lr:lang_1en,cdr:1,cd_min:11/01/2019,cd_max:11/01/2019,sbd:1&tbm=bks&source=lnms&sa=X&ved=2ahUKEwigq9Hrr8yEAxX8hq8BHRQdCTEQ0pQJegQIBhAK'

-------------------------------
------ creando dataframe ------
-------------------------------

100%|██████████| 1/1 [00:26<00:00, 26.41s/it]

-------------------------------
------ creando dataframe ------
-------------------------------

100%|██████████| 1/1 [00:30<00:00, 30.16s/it]

-------------------------------
------ creando dataframe ------
-------------------------------

100%|██████████| 1/1 [00:30<00:00, 30.42s/it]

-------------------------------
------ creando dataframe ------
-------------------------------

In [7]:
results[2]

{'name': 'ws3',
 'fecha': '2019-10-01',
 'ht': '15:36:31',
 't': 40.89471459388733,
 'result': [{'param': 'NEWMONT-NEM-NEWS',
   't': 0.0,
   'df':             company  Year  Month  Day        date media description title  \
   0  NEWMONT-NEM-NEWS  2019     10    1  2019/10/01

                                                   link  \
   0  https://www.mining.com/newmont-goldcorp-kicks-...

                                                   Text  word_count
   0  is located near chapleau ontario about 160 km ...         500  },
  {'param': 'AIR PRDS.& CHEMS.-APD-NEWS',
   't': 0.0,
   'df': Empty DataFrame
   Columns: []
   Index: []},
  {'param': 'FREEPORT-MCMORAN-FCX-NEWS',
   't': 0.0,
   'df': Empty DataFrame
   Columns: []
   Index: []},
  {'param': 'LINDE-LIN-NEWS',
   't': 0.0,
   'df': Empty DataFrame
   Columns: []
   Index: []},
  {'param': 'EXXON MOBIL-XOM-NEWS',
   't': 0.0,
   'df':                 company  Year  Month  Day        date media description title  \
   0  EXXON MOBIL-XOM-NEWS  2019     10    1  2019/10/01

                                                   link  \
   0  https://www.foxbusiness.com/money/exxon-mobil-...

                                                   Text  word_count
   0  fox news network llc all rights reserved faq n...         900  },
  {'param': 'SHERWIN-WILLIAMS-SHW-NEWS',
   't': 0.0,
   'df': Empty DataFrame
   Columns: []
   Index: []}]}